version: '3.7'
services:
  frontend:
    container_name: frontend
    build: ./web
    ports:
      - "8000:8080"
    volumes:
      - "./web:/app"
    links:
      - api
  api:
    container_name: backend
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - "./api:/app"
