version: '3.7'
services:
  frontend:
    build: ./web
    ports:
      - "8000:8080"
    volumes:
      - "./web:/app"
      - "/app/node_modules"
    links:
      - api
    networks:
      - backend
  api:
    build: ./api
    ports:
      - "3000"
    volumes:
      - "./api:/app"
      - "/app/node_modules"
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
